title: Sachin Kalsi's Blog
description: Programmer, Problem Solver
show_downloads: false
baseurl: "/blog/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://sachinkalsi.github.io" # change this to the base hostname & protocol for your site
email: "sachinkalsi15@gmail.com"
future: true
github:
  is_project_page: false
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

# social
author: "Sachin Kalsi"
image: /thumbnail-jumbo.png
twitter:
  username: sachin_kalsi
#  site:
defaults:
  -
    scope:
      path: "_posts"
    values:
      unpublished: true
      
gems: - jekyll-sitemap
